# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ""
email: hirobin_zhong@tamu.edu
description:  # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yuhao-zhong.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge

paginate: 5 # number of posts per page in pagination
paginate_path: "/page:num/"

# Collections
collections:
  posts:
    output: true # Enables posts to be rendered into _site folder

collections:
  papers:
    output: true
    permalink: /:collection/:path/

# Permalinks for posts
permalink: /:year/:month/:day/:title/

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Author Name"
      category: "default-category"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed

# Exclude these files and folders from build process
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"

# Options for kramdown Markdown processor
kramdown:
  input: GFM # GitHub-flavored Markdown
  syntax_highlighter_opts:
    block:
      line_numbers: true
